# 内置函数

### close
- 主要用来关闭channel

### len
- 用来求长度，比如string, array, slice, map, channel

### new
- 用来分配内存
- 主要用来分配值类型，比如int, struct。返回的是指针

### make
- 用来分配内存
- 主要用来分配引用类型，比如chan, map, slice

### append
- 用来追加元素到slice中
- 追加元素到数组中会报错
    ```go
    var a [2]int
    a = append(a, 10) // invalid argument: a (variable of type [2]int) is not a slice
    ```

### panic / recover
- 用来做错误处理
- recover：错误尝试恢复

- Go中没有异常处理机制(类似其他语言的try...catch...)，使用`panic/recover`模式来处理错误。
- `panic`可以在任何地方引发，但`recover`只有在`defer`调用的函数中有效。
(Go语言的哲学：所有错误必须显式地处理，所有的错误都会返回一个值)

```go
func funcA() {
    fmt.Println("func A")
}

func funcB() {
    panic("panic in B")
}

func funcC() {
    fmt.Println("funcC")
}

func main() {
    funcA()
    funcB()
    funcC()
}
```
输出:
```
$ go run test.go
func A
panic: panic in B

goroutine 1 [running]:
main.funcB(...)
        D:/workspace/test/src/go/worklog/test.go:10
main.main()
        D:/workspace/test/src/go/worklog/test.go:19 +0xa5
exit status 2
```
- 用处：出现严重错误，需要停止程序继续往下执行。e.g.:
    - 连接数据库失败
        ```go
        func funcB() {
            defer func() {
                fmt.Println("释放数据库链接...")
            }() // 这是一个立即执行函数
            panic("出现了严重的错误!!!") // 程序崩溃退出
            fmt.Println("b")
        }
        ```
- 用`recover`尝试恢复
    ```go
    func funcB() {
        defer func() {
            err := recover() //拿到panic的err
            // 如果程序出现了panic错误，可以通过recover恢复过来
            if err != nil {
                fmt.Println("recover in B")
            }
        }() // 这是一个立即执行函数
        panic("出现了严重的错误!!!") // 程序崩溃退出
    }
    ```
